version: '3.8'
services:
  order_router_service:
    build:
      context: ./OrderRouterServicePS
    container_name: order_router_service_ct
    depends_on:
      - rabbitmq_service
    ports:
      - "5002:5000"
  rabbitmq_service:
    image: rabbitmq:3.8.3
    container_name: rabbitmq_ct
    ports:
      - "5672:5672"
      - "15672:15672"
  inventory_service:
    build:
      context: ./InventoryServicePS
    container_name: inventory_service_ps_ct
    depends_on:
      - rabbitmq_service
    ports:
      - "5000:5000"
  order_record_service:
    build:
      context: ./OrderRecordServicePS
    container_name: order_record_service_ps_ct
    depends_on:
      - rabbitmq_service
    ports:
      - "5001:5000"